//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantManagement.Domain.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("RestaurantManagement.Core.Resources.CommonResource", typeof(CommonResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Validation_PriceShouldNotBeNegative {
            get {
                return ResourceManager.GetString("Validation_PriceShouldNotBeNegative", resourceCulture);
            }
        }
        
        public static string Validation_MaxMenuItemReached {
            get {
                return ResourceManager.GetString("Validation_MaxMenuItemReached", resourceCulture);
            }
        }
        
        public static string Validation_CannotDecreaseStock {
            get {
                return ResourceManager.GetString("Validation_CannotDecreaseStock", resourceCulture);
            }
        }
        
        public static string Validation_RestaurantNameShouldBeUnique {
            get {
                return ResourceManager.GetString("Validation_RestaurantNameShouldBeUnique", resourceCulture);
            }
        }
        
        public static string Validation_MaximumNumberOfRestaurant {
            get {
                return ResourceManager.GetString("Validation_MaximumNumberOfRestaurant", resourceCulture);
            }
        }
        
        public static string App_YouAreNotOwner {
            get {
                return ResourceManager.GetString("App_YouAreNotOwner", resourceCulture);
            }
        }
        
        public static string App_YouAreAlreadyOwner {
            get {
                return ResourceManager.GetString("App_YouAreAlreadyOwner", resourceCulture);
            }
        }
        
        public static string App_CategoryAlreadyExists {
            get {
                return ResourceManager.GetString("App_CategoryAlreadyExists", resourceCulture);
            }
        }
        
        public static string App_FoodNameAlreadyExists {
            get {
                return ResourceManager.GetString("App_FoodNameAlreadyExists", resourceCulture);
            }
        }
        
        public static string App_FoodNotFound {
            get {
                return ResourceManager.GetString("App_FoodNotFound", resourceCulture);
            }
        }
        
        public static string App_InvalidFoodTypes {
            get {
                return ResourceManager.GetString("App_InvalidFoodTypes", resourceCulture);
            }
        }
        
        public static string App_FoodIsAlreadyUsed {
            get {
                return ResourceManager.GetString("App_FoodIsAlreadyUsed", resourceCulture);
            }
        }
        
        public static string App_FoodTypeNotFound {
            get {
                return ResourceManager.GetString("App_FoodTypeNotFound", resourceCulture);
            }
        }
        
        public static string App_MenuNotFound {
            get {
                return ResourceManager.GetString("App_MenuNotFound", resourceCulture);
            }
        }
        
        public static string App_DuplicatedMenuItem {
            get {
                return ResourceManager.GetString("App_DuplicatedMenuItem", resourceCulture);
            }
        }
        
        public static string General_Canceled {
            get {
                return ResourceManager.GetString("General_Canceled", resourceCulture);
            }
        }
        
        public static string App_CategoryNotFound {
            get {
                return ResourceManager.GetString("App_CategoryNotFound", resourceCulture);
            }
        }
        
        public static string Validation_FieldIsRequired {
            get {
                return ResourceManager.GetString("Validation_FieldIsRequired", resourceCulture);
            }
        }
        
        public static string Authorization_NotAuthenticated {
            get {
                return ResourceManager.GetString("Authorization_NotAuthenticated", resourceCulture);
            }
        }
        
        public static string Validation_InvalidFieldValue {
            get {
                return ResourceManager.GetString("Validation_InvalidFieldValue", resourceCulture);
            }
        }
        
        public static string Validation_FieldShouldNotBeNegative {
            get {
                return ResourceManager.GetString("Validation_FieldShouldNotBeNegative", resourceCulture);
            }
        }
        
        public static string App_MenuItemNotFound {
            get {
                return ResourceManager.GetString("App_MenuItemNotFound", resourceCulture);
            }
        }
    }
}
