//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantManagement.Core.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("RestaurantManagement.Core.Resources.CommonResource", typeof(CommonResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Validation_PriceShouldNotBeNegative {
            get {
                return ResourceManager.GetString("Validation_PriceShouldNotBeNegative", resourceCulture);
            }
        }
        
        public static string Validation_MaxMenuItemReached {
            get {
                return ResourceManager.GetString("Validation_MaxMenuItemReached", resourceCulture);
            }
        }
        
        public static string Validation_CannotDecreaseStock {
            get {
                return ResourceManager.GetString("Validation_CannotDecreaseStock", resourceCulture);
            }
        }
        
        public static string Validation_RestaurantNameShouldBeUnique {
            get {
                return ResourceManager.GetString("Validation_RestaurantNameShouldBeUnique", resourceCulture);
            }
        }
        
        public static string Validation_MaximumNumberOfRestaurant {
            get {
                return ResourceManager.GetString("Validation_MaximumNumberOfRestaurant", resourceCulture);
            }
        }
        
        public static string Handler_YouAreNotOwner {
            get {
                return ResourceManager.GetString("Handler_YouAreNotOwner", resourceCulture);
            }
        }
    }
}
