services:
    system-sql:
        image: postgres:16.2
        environment:
            POSTGRES_PASSWORD: postgres
        volumes:
            - system-sql-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        command: |
            postgres
            -c wal_level=logical

    system-no-sql:
        image: mongo
        restart: always
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: mongo

    rabbit-mq:
        image: rabbitmq:3-management
        ports:
            - "15672:15672"
            - "5672:5672"
        volumes:
            - rabbit-mq-database:/var/lib/rabbitmq

    identity-api:
        image: identity-api
        build:
            context: .
            dockerfile: Services/Identity/Identity.Api/Dockerfile
        ports:
            - "5000:8080"
        environment:
            - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
            - ConnectionStrings__RelationalDatabase=${IDENTITY_DB}
            - IdentityConfiguration__IdentityPublicAddress=${IDENTITY_PUBLIC_ADDRESS}

        depends_on:
            - system-sql
            - rabbit-mq
        extra_hosts:
            - "host.docker.internal:host-gateway"

    restaurant-management-write-api:
        image: restaurant-management-write-api
        build:
            context: .
            dockerfile: Services/RestaurantManagement/Write/RestaurantManagement.Write.Api/Dockerfile
        ports:
            - "5010:8080"
        environment:
            - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
            - ConnectionStrings__Database=${RESTAURANT_MANAGEMENT_COMMAND_DB}
            - EventBusConfiguration__Host=rabbit-mq
            - IdentityConfiguration__Issuer=${IDENTITY_PUBLIC_ADDRESS}
        depends_on:
            - system-sql
            - rabbit-mq
        extra_hosts:
            - "host.docker.internal:host-gateway"

    restaurant-management-write-worker:
        image: restaurant-management-write-worker
        build:
            context: .
            dockerfile: Services/RestaurantManagement/Write/RestaurantManagement.Write.Worker/Dockerfile
        environment:
            - DOTNET_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
            - ConnectionStrings__Database=${RESTAURANT_MANAGEMENT_COMMAND_DB}
            - EventBusConfiguration__Host=rabbit-mq
        depends_on:
            - rabbit-mq
        extra_hosts:
            - "host.docker.internal:host-gateway"

    restaurant-management-read-api:
        image: restaurant-management-read-api
        build:
            context: .
            dockerfile: Services/RestaurantManagement/Read/RestaurantManagement.Read.Api/Dockerfile
        ports:
            - "5015:8080"
        environment:
            - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
            - ConnectionStrings__Database=${RESTAURANT_MANAGEMENT_QUERY_DB}
            - EventBusConfiguration__Host=rabbit-mq
            - IdentityConfiguration__Issuer=${IDENTITY_PUBLIC_ADDRESS}
        depends_on:
            - rabbit-mq
            - system-no-sql
        extra_hosts:
            - "host.docker.internal:host-gateway"

    website-bff:
        image: website-bff
        build:
            context: .
            dockerfile: ApiGateways/WebsiteBff/Dockerfile
        ports:
            - "5500:8080"
        environment:
            - ASPNETCORE_ENVIRONMENT=Compose
        extra_hosts:
            - "host.docker.internal:host-gateway"
networks:
    mongo:
        driver: bridge

volumes:
    system-sql-data:
        external: false
    rabbit-mq-database:
        external: false
